version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Allow up to 3 opened pull requests for github-actions versions.
    open-pull-requests-limit: 3
